### PR TITLE
Commit

### PR DESCRIPTION
**Pull request by rijalamisha21**
commit added

### CODE REVIEW

**Comment by wreck22** [comment]
tmro naam maathi table of contents maa aako xa ..tyo milaau

**Comment by rijalamisha21** [comment]
> 
> 
> tmro naam maathi table of contents maa aako xa ..tyo milaau

remove hudinw tyotw tala  contributor ma lekheko vayerw mathi akoxa

**Review by rijalamisha21 — COMMENTED** [review]
....

**Comment by wreck22** [comment]
last maa contributer maa naam lekhe paxi duichoti ENTER thhicha

**Comment by rijalamisha21** [comment]
> 
> 
> last maa contributer maa naam lekhe paxi duichoti ENTER thhicha

gare conflict ajhai resolve vakoxainw... 2 ta branch lai merge garerw push gareko teini hudinw

**Review by wreck22 — APPROVED** [review]

**Pull request merged**
