### PR TITLE
alias+intro_added

### PR DESCRIPTION
**Pull request by wreck22**

### CODE REVIEW

**Comment by Madara-coder** [comment]
Pawan oi tyo conflict fix garexi ma review gardinchu ....

**Comment by aomini** [comment]
@Madara-coder  bhai pheri error cha conflict ako pr haru chai fix garera matrai project ma todo ma rakha hai

**Comment by wreck22** [comment]
Dai ani pull request gareko time anusaar merge garnuparyo ni !!khaali aru ko agaadi merge gardera ta ma ta sadhai conflict milaaudai basnu ki k ho!!

**Review by Madara-coder — APPROVED** [review]

**Comment by aomini** [comment]
tmro sadhai herda conflict huncha ta ... merge gara na bhai... bhanda narisai hai.. aru ko agadi merge pachadi merge real workflow yehi ho.

**Pull request merged**
